#!/usr/bin/env python

import zmq
import random
import mraa

from flask import Flask
app = Flask(__name__)

def read_gpio(rid):
    x = mraa.Gpio(rid)
    value = x.read()
    return value

@app.route('/')
def hello_world():
    return 'leonard api'

@app.route('compressor')
def compressor():
    try:
        stat = read_gpio(2)
        stat = int(stat)
    except:
        return "Compressor Offline"

    if stat == 0:
        return "off"
    elif stat == 1:
        return "on"
    else:
        return "wtf"

@app.route('temp')
def temp():
    port = "5559"
    context = zmq.Context()
    socket = context.socket(zmq.REQ)
    socket.connect ("tcp://localhost:%s" % port)
    client_id = random.randrange(1,10005)
    socket.send ("templs %s" % client_id)
    #  Get the reply.
    celsius = socket.recv()
    celsius = float(celsius)
    fahrenheit = 9.0/5.0 * celsius + 32
    return fahrenheit

if __name__ == '__main__':
    app.run(host='0.0.0.0')
